-- ContabilBOT v5.0 Database Schema Setup
-- Run this in Supabase SQL Editor

-- ============================================
-- EXISTING TABLES (from v4.0)
-- ============================================

-- financial_profile table
CREATE TABLE IF NOT EXISTS financial_profile (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT DEFAULT 1,
    budget NUMERIC DEFAULT 5000,
    goals TEXT DEFAULT 'Save money',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Insert default profile if not exists
INSERT INTO financial_profile (user_id, budget, goals)
SELECT 1, 5000, 'Save money'
WHERE NOT EXISTS (SELECT 1 FROM financial_profile WHERE user_id = 1);

-- expenses table (should already exist)
-- ALTER TABLE expenses ADD COLUMN IF NOT EXISTS user_note TEXT;

-- ============================================
-- NEW TABLES FOR v5.0
-- ============================================

-- Chat history for persistent AI context
CREATE TABLE IF NOT EXISTS chat_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT DEFAULT 1,
    role TEXT NOT NULL CHECK (role IN ('user', 'assistant', 'system')),
    content TEXT NOT NULL,
    tool_calls JSONB,
    tool_results JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Income tracking table
CREATE TABLE IF NOT EXISTS income (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT DEFAULT 1,
    amount NUMERIC NOT NULL,
    source TEXT,
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Subscriptions tracking table
CREATE TABLE IF NOT EXISTS subscriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT DEFAULT 1,
    name TEXT NOT NULL,
    amount NUMERIC NOT NULL DEFAULT 0,
    billing_cycle TEXT DEFAULT 'monthly',
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Savings goals tracking table
CREATE TABLE IF NOT EXISTS savings_goals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT DEFAULT 1,
    name TEXT NOT NULL,
    target_amount NUMERIC NOT NULL DEFAULT 0,
    current_amount NUMERIC DEFAULT 0,
    deadline TIMESTAMP WITH TIME ZONE,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ============================================
-- INDEXES FOR PERFORMANCE
-- ============================================

CREATE INDEX IF NOT EXISTS idx_chat_history_user ON chat_history(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_expenses_created ON expenses(created_at);
CREATE INDEX IF NOT EXISTS idx_expenses_category ON expenses(category);
CREATE INDEX IF NOT EXISTS idx_income_created ON income(created_at);
CREATE INDEX IF NOT EXISTS idx_subscriptions_active ON subscriptions(is_active);
CREATE INDEX IF NOT EXISTS idx_goals_active ON savings_goals(is_active);

-- ============================================
-- INITIAL DATA
-- ============================================

-- Insert default savings goal if not exists
INSERT INTO savings_goals (name, target_amount, current_amount)
SELECT 'Emergency Fund', 10000, 0
WHERE NOT EXISTS (SELECT 1 FROM savings_goals WHERE name = 'Emergency Fund');

-- Insert example subscriptions if not exists
INSERT INTO subscriptions (name, amount, billing_cycle)
SELECT 'Netflix', 8.99, 'monthly'
WHERE NOT EXISTS (SELECT 1 FROM subscriptions WHERE name = 'Netflix');

-- ============================================
-- SAMPLE INCOME ENTRIES (Optional - for testing)
-- ============================================

-- This will only insert if income table is empty
INSERT INTO income (amount, source)
SELECT 500, 'Test Income'
WHERE NOT EXISTS (SELECT 1 FROM income LIMIT 1);

-- ============================================
-- RLS POLICIES (Row Level Security)
-- ============================================

-- Enable RLS on all tables
ALTER TABLE financial_profile ENABLE ROW LEVEL SECURITY;
ALTER TABLE chat_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE income ENABLE ROW LEVEL SECURITY;
ALTER TABLE subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE savings_goals ENABLE ROW LEVEL SECURITY;

-- Create policies allowing user_id = 1 access (single user app)
CREATE POLICY "Allow access for user 1" ON financial_profile
    FOR ALL USING (user_id = 1);

CREATE POLICY "Allow access for user 1" ON chat_history
    FOR ALL USING (user_id = 1);

CREATE POLICY "Allow access for user 1" ON income
    FOR ALL USING (user_id = 1);

CREATE POLICY "Allow access for user 1" ON subscriptions
    FOR ALL USING (user_id = 1);

CREATE POLICY "Allow access for user 1" ON savings_goals
    FOR ALL USING (user_id = 1);

-- Done! Run this script in Supabase SQL Editor.
