-- ContabilBOT Database Schema Setup
-- Run this in Supabase SQL Editor

-- Create financial_profile table for user budget and goals
CREATE TABLE IF NOT EXISTS financial_profile (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT DEFAULT 1,
    budget NUMERIC DEFAULT 5000,
    goals TEXT DEFAULT 'Save money',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Insert default profile if not exists
INSERT INTO financial_profile (user_id, budget, goals)
SELECT 1, 5000, 'Save money'
WHERE NOT EXISTS (SELECT 1 FROM financial_profile WHERE user_id = 1);

-- Add user_note column to expenses table
ALTER TABLE expenses ADD COLUMN IF NOT EXISTS user_note TEXT;

-- Optional: Create index for faster category queries
CREATE INDEX IF NOT EXISTS idx_expenses_category ON expenses(category);
CREATE INDEX IF NOT EXISTS idx_expenses_created_at ON expenses(created_at);
